[mypy]
ignore_missing_imports = True
disallow_untyped_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = False
strict_optional = True
mypy_path = megano
exclude = migrations/|tests/|admin.py|apps.py|management/commands/initdata.py
disable_error_code = var-annotated,import-untyped,attr-defined
