ORDER_STATUS_ACCEPTED = "accepted"
ORDER_STATUS_PAID = "paid"
ORDER_STATUS_IN_DELIVERY = "in_delivery"
ORDER_STATUS_DELIVERED = "delivered"
ORDER_STATUS_CANCELLED = "cancelled"

ORDER_STATUS_CHOICES = [
    (ORDER_STATUS_ACCEPTED, "Accepted"),
    (ORDER_STATUS_PAID, "Paid"),
    (ORDER_STATUS_IN_DELIVERY, "In Delivery"),
    (ORDER_STATUS_DELIVERED, "Delivered"),
    (ORDER_STATUS_CANCELLED, "Cancelled"),
]

DELIVERY_TYPE_STANDARD = "standard"
DELIVERY_TYPE_EXPRESS = "express"

DELIVERY_TYPE_CHOICES = [
    (DELIVERY_TYPE_STANDARD, "Standard"),
    (DELIVERY_TYPE_EXPRESS, "Express"),
]

PAYMENT_TYPE_ONLINE = "online"
PAYMENT_TYPE_CASH = "cash"

PAYMENT_TYPE_CHOICES = [
    (PAYMENT_TYPE_ONLINE, "Online"),
    (PAYMENT_TYPE_CASH, "Cash"),
]
